version: '3.8'

services:
  rickandmorty-app:
    container_name: rickandmorty-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./rickandmorty:/app